### PR TITLE
Fixed problem with starting OpenHub as standalone application

### PR DESCRIPTION
**Pull request by hanusto**
Explicitly mark environment (application) as web-based and avoid to exception: `@ConditionalOnWebApplication` (required) not a web application.

Issue: NOJIRA

### CODE REVIEW

**Comment by hanusto** [comment]
It is possible to test this in Tomcat deployment? @kkovarik or @pjuza ? Thx.

**Comment by kkovarik** [comment]
@hanusto great, tested on local tomcat, seems to be working ok, spring context loads fine.

**Comment by hanusto** [comment]
One more known issue for standalone - non visible WSDL services. It is necessary to be fixed.

**Comment by pjuza** [comment]
I have also tested on local tomcat, it works fine.
Web services are working but OHF started without admin console module.

**Review by kkovarik — APPROVED** [review]

**Pull request merged**
